name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 33 21 */10 * *

jobs:
  p2r-test:
    name: Unit tests for paper2remarkable
    runs-on: [ 'ubuntu-latest' ]
    strategy:
      matrix:
        py: [ '3.8', '3.11' ]

    steps:
      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit test script
        run: ./.github/scripts/test_p2r.sh
        shell: bash

      - name: Run code quality tests (black)
        uses: psf/black@stable

      - name: Run code quality tests (isort)
        uses: jamescurtin/isort-action@master
